### ISSUE TITLE
enhancement request: super chat and membership columns

### ISSUE THREAD

**Issue by mlturner88** [PoiScript/HoloStats#369]
If possible, I would like to see the super chat and membership stats in addition to views and subscriptions. I am not 100% sure if this is possible or not.

**Comment by PoiScript** [comment]
Thanks for the suggestion, and yes, it's totally possible but a little bit complicated. I'll look into it if I have time. Stay tuned for updates. :)

**Comment by siikamiika** [comment]
I've spent quite some time with the live chat replay format. There are examples of how to parse it [here (JS)](https://github.com/siikamiika/youtube-live-archive/blob/master/public/js/video/live-chat/YoutubeLiveChatParser.js) and [here (Python)](https://github.com/siikamiika/scripts/tree/master/danmaku). I've also been thinking of adding similar statistics to my own project once I import the chats to the database, but now I'm keeping an eye on this project because I found it :smile:

I added basic downloading support to [the unlucky youtube downloader](https://github.com/blackjack4494/yt-dlc/blob/master/youtube_dlc/downloader/youtube_live_chat.py) before it was taken down, and there's a more comprehensive project for the purpose [here](https://github.com/taizan-hokuto/pytchat).

Hope this helps, feel free to ask any details!

**Comment by mlturner88** [comment]
> I've spent quite some time with the live chat replay format.

@siikamiika Is this really the only way to implement this? The example I was thinking of is the metrics [Playboard](https://playboard.co/en) has available. Looking through chat replays falls apart when streams are not archived and that would mean we would have to collect the data and store it somewhere.

**Comment by siikamiika** [comment]
@mlturner88 I don't know how Playboard does it, but I guess it's also just scraping the information from chat unless they have contracts with individual streamers/agencies. The [official YouTube API][1] only supports getting your own superchat details for the past 30 days. Playboard [mentions][2] that they have data for unarchived videos too since January 10, 2020, which I'd guess means that they monitor all live streamers and scrape the superchats live. If the only information needed is the aggregate amount of superchat earnings, you could just scrape that from Playboard.

[1]: https://developers.google.com/youtube/v3/live/docs/superChatEvents
[2]: https://playboard.co/en/about

**Comment by mlturner88** [comment]
@siikamiika That's not a bad idea. We can take advantage of their hard work. Perhaps we can do a PR.

**Comment by siikamiika** [comment]
@mlturner88 While that would be a far easier way to achieve just this feature, you'd lose any possible future development such as plotting superchat earnings or 草 comments over stream timeline. I'm personally more interested in creating something that doesn't exist in other services although gathering information in one place and archival are some advantages.

Anyway maybe @PoiScript has something to say about how/if this should be done, I'm just trying to give ideas.

**Comment by PoiScript** [comment]
Sorry to keep you guys waiting.

I recently added support for collecting and showing live chat statistics data. Now you can see the distribution of both live chat and paid live chat (superchat and supersticker) for newly stream.

[Example](https://holo.poi.cat/stream/SrHRlSW7as0)

<img width="1101" alt="Screen Shot 2021-12-30 at 2 27 31 PM" src="https://user-images.githubusercontent.com/17513314/147727167-08b1914c-2e73-4ddc-a273-9d33cb11605c.png">

@siikamiika 

> such as plotting superchat earnings or 草 comments over stream timeline. 

It'll take significant amount of space for storing every single live chat message, so I only keep the paid live chat message in database. So currently there's no way for plotting 草 comments, but we can do that for superchat.

I'm going to close this issue, feel free to open a new ticket if you have any new idea!
