### ISSUE TITLE
Official channels missing and other

### ISSUE THREAD

**Issue by krisszt** [PoiScript/HoloStats#377]
Hello!

The official channels for [HoloStars](https://www.youtube.com/channel/UCWsfcksUUpoEvhia0_ut0bA), [Indonesia](https://www.youtube.com/channel/UCfrWoRGlawPQDQxxeIDRP0Q) and [EN](https://www.youtube.com/channel/UCotXwY6s8pWmuWd_snKYjhg/featured) are missing from the lineup.

Also, since the China branch is possibly being dissolved but leaving the girls with their names, avatars, etc., will they be moved to the "Others" tab? (Maybe only if they stay independent?) (Cover hadn't announced anything yet, but individuals had already spoken. [Civia](https://www.reddit.com/r/Hololive/comments/jfwkqs/civia_talked_about_the_future_of_holocn/), [Doris](https://www.reddit.com/r/VirtualYoutubers/comments/jhsn17/doris_of_hololive_has_announced_two_major/) and [Artia](https://twitter.com/artia_ow/status/1320445451594858496?s=21) ([link2](https://www.twitlonger.com/show/n_1srepvl)) ) And, tangentially related due to Artia, will Twitch data be included some time later?

**Comment by PoiScript** [comment]
Thanks for suggestions,

> The official channels for HoloStars, Indonesia and EN are missing from the lineup.

I do know there are channels for HoloStars, HoloId, and HoloEn. I decided not to include them because they're less active compared to the one of HoloJp. I want to focus more on active channels, and let me know if you think otherwise.

> will they be moved to the "Others" tab? (Maybe only if they stay independent?)

Yes, I'll definitely keep their channels, and move the "Others" category. I also have heard some rumors that some of them may graduate. So I won't change anything until everything is finally settled.

> will Twitch data be included some time later

Unfortunately, there're no plan yet. I personally don't watch twitch, so actually don't know if it's even possible. I'll look into it once I have time. 

I'm going to close this issue, but feel free to reopen if you still have some questions. :P
