### ISSUE TITLE
Search by date/Criteria for vtubers

### ISSUE THREAD

**Issue by krisszt** [PoiScript/HoloStats#526]
Is a "search by date" possible for the site? Or would it require too much time/overhaul as to be not worth it? (Search by month would be enough for me.)

What are the criteria for vtubers to be added to the "Others" tab? Since one of them seems to be "interact with Hololive members with some regularity", I'd nominate [Pochimaru](https://www.youtube.com/channel/UC22BVlBsZc6ta3Dqz75NU6Q/videos), Reine's artist, who started collabing with the Indonesian and English side,

**Comment by PoiScript** [comment]
> Is a "search by date" possible for the site? Or would it require too much time/overhaul as to be not worth it? (Search by month would be enough for me.)

I just uploaded a new version of website, you're able to filter stream by selecting date range now. :) Try to refresh the browser or clear cache if the option donnot show up.

> What are the criteria for vtubers to be added to the "Others" tab? Since one of them seems to be "interact with Hololive members with some regularity", I'd nominate [Pochimaru](https://www.youtube.com/channel/UC22BVlBsZc6ta3Dqz75NU6Q/videos), Reine's artist, who started collabing with the Indonesian and English side,

Thank you for suggesting, I've added pochimaru. Actually, there's no rule at all. Mostly I added vtubers due to personal interest. So feel free to suggest more. 😉
